# Generated by Django 5.2.10 on 2026-02-02 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookassignment",
            options={"ordering": ["-issue"]},
        ),
        migrations.RemoveField(
            model_name="bookassignment",
            name="assigned_at",
        ),
        migrations.RemoveField(
            model_name="bookassignment",
            name="person_name",
        ),
        migrations.RemoveField(
            model_name="bookassignment",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="bookassignment",
            name="sell_price",
        ),
        migrations.RemoveField(
            model_name="bookassignment",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="bookassignment",
            name="issue",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookassignment",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookassignment",
            name="status",
            field=models.CharField(
                choices=[("issued", "Issued"), ("returned", "Returned")],
                default="issued",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookassignment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="books.student",
            ),
        ),
        migrations.AddField(
            model_name="bookassignment",
            name="transaction_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
